### ISSUE TITLE
Stops audio recording after a few seconds

### ISSUE THREAD

**Issue by michaguenther** [kastldratza/zoomrec#23]
Unfortunately the audio recording of the video stops after 5-10 seconds of recording. Tested it multiple times, but can not get it working. The problem occurs no matter what the debug flag is set to. Also tested it with the default screen size of 1024x576.
System: Ubuntu 20.04.2.
Docker version: 19.03.8

My docker-compose setup is the following:
```yaml
version: "3.5"
services:
  app:
    image: zoomrec:latest
    container_name: zoomrec
    build: .
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - VNC_PW=test1234
      - VNC_RESOLUTION=1920x1080
      # in order to debug better
      # - DEBUG=True
    volumes:
      - ./recordings:/home/zoomrec/recordings
      - ./example/meetings.csv:/home/zoomrec/meetings.csv:ro
    ports:
      - 5901:5901
```
